AS4: checker.h File Reference
checker.h File Reference
checks arguments for all functions
#include "wave.h"
#include <stdbool.h>
#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
Macros
#define CHECKER
Functions
bool isNumber (char *str)
checks if a string represents a number
bool checkOption (char *argv[])
checks if the option from the command line is valid
bool isValidWaveFile (char *fileName)
checks if the wave file is valid
char ** getValidFiles (char *argv[], int *numOfValidFiles)
checks and returns the Valid Files from the argument line
bool checkTimings (char *fileName, int start, int end)
checks if the timings given are in range with the length of the wave file and that the start time is smaller than the end time
bool isTextFile (char *fileName)
checks if the file name has a .txt extension
bool txtFitsWav (char *wavFileName, char *txtFileName)
check if the text file fits to get encoded in the wave file
Detailed Description
checks arguments for all functions
Author
Nikolas Theodorou (ntheo.nosp@m.d10@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-11-29
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details in the COPYING file.
See license in COPYING file.
Copyright
Copyright (c) 2021
Macro Definition Documentation
CHECKER
#define CHECKER
Function Documentation
checkOption()
bool checkOption (char * argv[])
checks if the option from the command line is valid
Parameters
argv arguments from command line
Returns
true
false
{
         if(strcmp(argv[1],"-list")!=0 || strcmp(argv[1],"-mono")!=0 || strcmp(argv[1],"-mix")!=0 || strcmp(argv[1],"-chop")!=0
         || strcmp(argv[1],"-reverse")!=0 || strcmp(argv[1],"-encodeText")!=0 || strcmp(argv[1],"-decodeText")!=0 || strcmp(argv[1],"-changeSpeed")!=0)
             return false;
      return true;
 }
Referenced by main().
checkTimings()
bool checkTimings (char * fileName, int start, int end)
checks if the timings given are in range with the length of the wave file and that the start time is smaller than the end time
Parameters
fileName the name of the wave file
start the start time of chopping
end the end time of chopping
Returns
true
false
{
     if(start>end){
         printf("start time is bigger than end time\n");
         return false;
     }
     bool valid = true;
     WAVE *wave =(WAVE*) malloc(sizeof(WAVE));
     initializeFromFile(wave,fileName);
     int waveTime = (int) wave->dataChunk->subchunk2Size /(int) wave->fmtChunk->byteRate;
     if(start > waveTime || end > waveTime || start < 0|| end < 0 ){
             printf("timings given are not in range of wave file's length, wave's length is %d seconds\n",waveTime);
             valid = false;
             goto free;
     }
     free:
     deallocWave(wave);
     free(wave);
     return valid;
 }
References fmt_chunk::byteRate, wave::dataChunk, deallocWave(), wave::fmtChunk, initializeFromFile(), and data_chunk::subchunk2Size.
Referenced by main().
getValidFiles()
char** getValidFiles (char * argv[], int * numOfValidFiles)
checks and returns the Valid Files from the argument line
Parameters
argv arguments from command line
numOfValidFiles number of valid files
Returns
char** a teble with all valid files
{
     int i=2;
     int numOfFiles=0;
     numOfValidFiles[0]=0;
     while(argv[i]!=NULL){
         numOfFiles++;
         i++;
     }
     char **validFiles= malloc(numOfFiles*sizeof(char*));
     for(i=0;i<numOfFiles;i++){
         char *fileName=argv[2+i];
         if(isValidWaveFile(fileName)){
             validFiles[numOfValidFiles[0]]=fileName;
             numOfValidFiles[0]++;
         }
     }
     return validFiles;
 }
References isValidWaveFile().
Referenced by main().
isNumber()
bool isNumber (char * str)
checks if a string represents a number
Parameters
str
Returns
true
false
{
     for (int i = 0; str[i]!= '\0'; i++)
     {
         if (!isdigit(str[i]) && str[i]!='.')
               return false;
     }
     return true;
 }
Referenced by isTextFile(), isValidWaveFile(), and main().
isTextFile()
bool isTextFile (char * fileName)
checks if the file name has a .txt extension
Parameters
fileName the .txt file
Returns
true
false
{
     if(isNumber(fileName))
         return false;
     int len = strlen(fileName);
     if(len<4){
         printf("invalid filename  \"%s\": it's too short\n",fileName);
         return false;
     }
     char *fileExtension = &fileName[len-4];
     if(strcmp(fileExtension,".txt")!=0){
         printf("invalid file \"%s\": file extension is not .txt\n",fileName);
         return false;
     }
     return true;
 }
References isNumber().
Referenced by main().
isValidWaveFile()
bool isValidWaveFile (char * fileName)
checks if the wave file is valid
Parameters
fileName wave file
Returns
true
false
{
     if(isNumber(fileName))
         return false;
     int len = strlen(fileName);
     if(len<4){
         printf("invalid filename \"%s\": it's too short\n",fileName);
         return false;
     }
     char *fileExtension = &fileName[len-4];
     if(strcmp(fileExtension,".wav")!=0){
         if(strcmp(fileExtension,".txt")==0)
             return false;
         printf("invalid filename \"%s\": it's not a .wav file\n",fileName);
         return false;
     }
     bool valid= true;
     WAVE *wave = NULL;
     wave= (WAVE*) malloc(sizeof(WAVE));
     initializeFromFile(wave,fileName);
     if(wave->fmtChunk->audioFormat!=1){
         printf("invalid file \"%s\": it seems to be compressed (PCM != 1)\n",fileName);
         valid = false;
         goto free;
     }
     if(wave->fmtChunk->numChannels > 2){
         printf("invalid file \"%s\": file has more than 2 channels\n",fileName);
         valid = false;
         goto free;
     }
     free:
     deallocWave(wave);
     free(wave);
     return valid;
 }
References fmt_chunk::audioFormat, deallocWave(), wave::fmtChunk, initializeFromFile(), isNumber(), and fmt_chunk::numChannels.
Referenced by getValidFiles().
txtFitsWav()
bool txtFitsWav (char * wavFileName, char * txtFileName)
check if the text file fits to get encoded in the wave file
Parameters
wavFileName
txtFileName
Returns
true
false
bits in text file should not be more than the bytes in the data of the wave file
{
     bool fits=true;
     FILE *tfp=NULL;
     tfp = fopen(txtFileName,"rb");
     if(tfp == NULL){
         printf("could not open file %s\n",txtFileName);
         return false;
     }
     WAVE *wave=(WAVE*) malloc(sizeof(WAVE));
     initializeFromFile(wave,wavFileName);
     int textSize=0;
     fseek(tfp,0,SEEK_END);
     textSize = ftell(tfp);       //count file size
     if (textSize == 0){     //check if file is empty and ouput a warning message
         printf("file \"%s\" is empty\n",txtFileName);
         fits=false;
         goto free;
     }
     if(textSize*8 > wave->dataChunk->subchunk2Size){
         printf("cannot fit text file to wave file\n");
         fits=false;
         goto free;
     }
     free:
     fclose(tfp);
     deallocWave(wave);
     free(wave);
     return fits;
 }
References wave::dataChunk, deallocWave(), initializeFromFile(), and data_chunk::subchunk2Size.
Referenced by main().