AS4: chop.h File Reference
chop.h File Reference
trims wave file
#include "wave.h"
Functions
void chop (char **files, int numOfFiles, int start, int end)
exports a trimmed wave file
Detailed Description
trims wave file
Author
Nikolas Theodorou (ntheo.nosp@m.d10@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-11-29
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details in the COPYING file.
See license in COPYING file.
Copyright
Copyright (c) 2021
Function Documentation
chop()
void chop (char ** files, int numOfFiles, int start, int end)
exports a trimmed wave file
Parameters
files table of files, it uses only the first one.
numOfFiles number of files in **files
start start time of trimmed wave
end end time of trimmed wave
redefine headers
copy data from original wave to the chopped wave from startChunk to endChunk
export trimmed to file -> chopped-<filename>
{
     int i;
     for(i=0;i<numOfFiles;i++){
         WAVE *origWave = (WAVE*) malloc(sizeof(WAVE));
         WAVE *chopWave = (WAVE*) malloc(sizeof(WAVE));
         initializeFromFile(origWave,files[i]);
         initializeFromFile(chopWave,files[i]);
         free(chopWave->dataChunk->data);
         int startChunk= start*origWave->fmtChunk->byteRate;
         int endChunk= end*origWave->fmtChunk->byteRate;
         chopWave->dataChunk->subchunk2Size= endChunk-startChunk;
         chopWave->riffChunk->chunkSize=  origWave->riffChunk->chunkSize - origWave->dataChunk->subchunk2Size + chopWave->dataChunk->subchunk2Size;
         chopWave->dataChunk->data = (byte *)malloc( (endChunk-startChunk) * sizeof(byte));
         memcpy(&chopWave->dataChunk->data[0], &origWave->dataChunk->data[startChunk], endChunk-startChunk);
         exportWave(files[i],chopWave,"chopped-");
         deallocWave(chopWave);
         free(chopWave);
         deallocWave(origWave);
         free(origWave);
     }
 }
References fmt_chunk::byteRate, riff_chunk::chunkSize, data_chunk::data, wave::dataChunk, deallocWave(), exportWave(), wave::fmtChunk, initializeFromFile(), wave::riffChunk, and data_chunk::subchunk2Size.
Referenced by main().