AS4: decode.c File Reference
decode.c File Reference
implements decode.h
#include "decode.h"
#include "encode.h"
Functions
void decode (char *waveFile, int len, char *textFile)
decodes an encoded text from a wavefile
Detailed Description
implements decode.h
Author
Nikolas Theodorou (ntheo.nosp@m.d10@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-11-29
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details in the COPYING file.
See license in COPYING file.
Copyright
Copyright (c) 2021
Function Documentation
decode()
void decode (char * waveFile, int len, char * textFile)
decodes an encoded text from a wavefile
Parameters
waveFile wave file
len length of message
textFile output file
builds a character and then inserts it to the text
{
     WAVE *wave = (WAVE*) malloc(sizeof(WAVE));
     initializeFromFile(wave,waveFile);
     char* text = (char*)calloc(1,len+1);
     FILE *fp;
     fp = fopen(textFile, "w");
     int *permutation;
     permutation=createPermutationFunction(wave->dataChunk->subchunk2Size, KEY);
     int byte,bit,u,x;
     int permIndex=0;
     for(byte=0; byte<1+len;byte++){
         char c=NULL;
         for(bit=7; bit>=0;bit--){ //builds character bit by bit
             x=permutation[permIndex++];
             u= wave->dataChunk->data[x];
             c |= u << bit;
         }
         strncat(text,&c,1);
         c=NULL;
     }
     fprintf(fp,text);
     fclose(fp);
     deallocWave(wave);
     free(wave);
     free(text);
     free(permutation);
 }
References createPermutationFunction(), data_chunk::data, wave::dataChunk, deallocWave(), initializeFromFile(), KEY, and data_chunk::subchunk2Size.
Referenced by main().