AS4: encode.h File Reference
encode.h File Reference
used to encode a text file to a wav file
#include "wave.h"
Macros
#define KEY 585
Functions
void encode (char *waveFile, char *textFile)
read a wav file and a text file, and based on a random table it places the text bits into the wav file
int getBit (char *m, int n)
finds the bit in the specific location and returns it
int * createPermutationFunction (int N, unsigned int systemkey)
Create a table and shuffle it randomly.
Detailed Description
used to encode a text file to a wav file
Author
Panayiotis Fotiadis 1031373
Version
0.1
Date
2021-11-29
Copyright
Copyright (c) 2021
Macro Definition Documentation
KEY
#define KEY 585
Function Documentation
createPermutationFunction()
int* createPermutationFunction (int N, unsigned int systemkey)
Create a table and shuffle it randomly.
Parameters
N size of data
systemkey srand key
Returns
int* shuffled table
{
     int *permutation = (int*)malloc(N*sizeof(int)); //used to store the shuffled numbers
     int i,index1,index2,temp;   //i used for loops, index1 and index2 are the position of numbers that will get swapped
     srand(systemkey);   //create srand with systemkey
     for(i=0;i<N;i++){
         permutation[i]=i;   //fill permutation
     }
     for (i=0;i<N;i++){
         index1 = rand() % N-1;
         index2 = rand() % N-1;
         temp = permutation[index1];     //create 2 random ints and swap number their indexes
         permutation[index1] = permutation[index2];
         permutation[index2] = temp;
     }
     return permutation;
 }
Referenced by decode(), and encode().
encode()
void encode (char * waveFile, char * textFile)
read a wav file and a text file, and based on a random table it places the text bits into the wav file
Parameters
waveFile imports a wave file
textFile import a text file
{
     char *text = (char*)calloc(sizeof(char),2); //used to store text containt
     FILE *fp;
     fp = fopen(textFile, "r");  //read text
     int i=0;
     while(!feof(fp)){
         fscanf(fp,"%c", &text[i]);
         i++;
         text = (char*)realloc(text, i+1); //fill text with textFile containt
     }
     fclose(fp);
     WAVE *wave =NULL;
     wave = (WAVE*)malloc(sizeof(WAVE));
     initializeFromFile(wave, waveFile); //create WAVE and fill it with waveFile data
     int *permutation;
     permutation = createPermutationFunction(wave->dataChunk->subchunk2Size, KEY); //get table with shuffled positions
     int u,x;
     for(i=0;i<(1+strlen(text))*8;i++){
         u = getBit(text,i); //get next bit of string
         x = permutation[i]; //get the position that the bit will be stored
         wave->dataChunk->data[x]=u; //store the bit in the wave data
     }
     exportWave(waveFile,wave,"encoded-");   //export the encoded wave
     deallocWave(wave);
     free(wave);
     free(text);
     free(permutation);
 }
References createPermutationFunction(), data_chunk::data, wave::dataChunk, deallocWave(), exportWave(), getBit(), initializeFromFile(), KEY, and data_chunk::subchunk2Size.
Referenced by main().
getBit()
int getBit (char * m, int n)
finds the bit in the specific location and returns it
Parameters
m text file
n bit position
Returns
int bit
{
     int byteCal = n/8;  //calculate the byte that the bit it looks for exist
     int bitCal = (7-(n%8)); //calculate the position of the bit in the specific byte
     int bit = (m[byteCal]>>bitCal&1);   //shift the byte to the specific bit and save its value
     return bit; //return the bit
 }
Referenced by encode().