AS4: reverse.h File Reference
reverse.h File Reference
reverse the data of the wave
#include "wave.h"
Functions
void reverseWave (char **inputFiles, int numOfFiles)
finds if the wave is stereo or mono and jumps to specific function
void reverseStereo (WAVE *wave, char *inputFile)
reverse a stereo wave
void reverseMono (WAVE *wave, char *inputFile)
reverse a mono wave
void createReverseWave (WAVE *reverseWave, char *inputFile)
create the reverse wave with empty data
Detailed Description
reverse the data of the wave
Author
Panayiotis Fotiadis 1031373
Version
0.1
Date
2021-11-29
Copyright
Copyright (c) 2021
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details in the COPYING file.
See license in COPYING file.
Copyright
Copyright (c) 2021
Function Documentation
createReverseWave()
void createReverseWave (WAVE * reverseWave, char * inputFile)
create the reverse wave with empty data
Parameters
reverseWave wave to store the data
inputFile input file of original wave
{
     initializeFromFile(reverseWave, inputFile); //copy the data fro file
     free(reverseWave->dataChunk->data); //free the data
     reverseWave->dataChunk->data = (byte *)malloc(reverseWave->dataChunk->subchunk2Size * sizeof(byte));    //assign them new free space
 }
References initializeFromFile(), and reverseWave().
Referenced by reverseMono(), and reverseStereo().
reverseMono()
void reverseMono (WAVE * wave, char * inputFile)
reverse a mono wave
Parameters
wave original wave
inputFile input file of original wave
{
     WAVE *reverseWave =NULL;
     reverseWave = (WAVE*)malloc(sizeof(WAVE));
     createReverseWave(reverseWave, inputFile);
     int i;
     int waveCounter = 0;
     printf("%d\t%d\n", wave->dataChunk->subchunk2Size- (wave->fmtChunk->bitsPerSample/8), waveCounter);
     for(i=wave->dataChunk->subchunk2Size- (wave->fmtChunk->bitsPerSample/8) ; i>=0; i = i-(wave->fmtChunk->bitsPerSample/8)){   //loop from end to begin moving 2 samples(left and right) each time
         memcpy(&reverseWave->dataChunk->data[i], &wave->dataChunk->data[waveCounter], wave->fmtChunk->bitsPerSample/8); //copy both channels from original wave to reverse wave
         waveCounter = waveCounter + wave->fmtChunk->bitsPerSample/8;    //move to next 2 samples
     }
     exportWave(inputFile, reverseWave,"reverse-");  //export wave
     deallocWave(reverseWave);
     free(reverseWave);
     reverseWave =NULL;
 }
References fmt_chunk::bitsPerSample, createReverseWave(), data_chunk::data, wave::dataChunk, deallocWave(), exportWave(), wave::fmtChunk, reverseWave(), and data_chunk::subchunk2Size.
Referenced by reverseWave().
reverseStereo()
void reverseStereo (WAVE * wave, char * inputFile)
reverse a stereo wave
Parameters
wave original wave
inputFile input file of original wave
{
     WAVE *reverseWave =NULL;
     reverseWave = (WAVE*)malloc(sizeof(WAVE));      //create new wave to store the reversed data
     createReverseWave(reverseWave, inputFile);      //copy the data from file and free the data segment
     int i;
     int waveCounter = 0;    //used as index for the data of the original wave
     for(i=wave->dataChunk->subchunk2Size- (wave->fmtChunk->bitsPerSample/4) ; i>=0; i = i-(wave->fmtChunk->bitsPerSample/4)){   //loop from end to begin from sample to sample
         memcpy(&reverseWave->dataChunk->data[i], &wave->dataChunk->data[waveCounter], wave->fmtChunk->bitsPerSample/4); //copy the data from origianl to reverseWave
         waveCounter = waveCounter + wave->fmtChunk->bitsPerSample/4;    //jump to next byte
     }
     exportWave(inputFile, reverseWave,"reverse-");  //export Wave
     deallocWave(reverseWave);
     free(reverseWave);
     reverseWave =NULL;
 }
References fmt_chunk::bitsPerSample, createReverseWave(), data_chunk::data, wave::dataChunk, deallocWave(), exportWave(), wave::fmtChunk, reverseWave(), and data_chunk::subchunk2Size.
Referenced by reverseWave().
reverseWave()
void reverseWave (char ** inputFiles, int numOfFiles)
finds if the wave is stereo or mono and jumps to specific function
Parameters
inputFiles stores all wave files
numOfFiles number of stored files
{
     int i;
     WAVE *wave = NULL;
     for (i = 0; i < numOfFiles; i++){       //loop throught each file
         wave = (WAVE*)malloc(sizeof(WAVE));
         initializeFromFile(wave,inputFiles[i]);     //copy the file data to wave
         if(wave->fmtChunk->numChannels == 1){   //if wave is mono
             reverseMono(wave, inputFiles[i]);
         }
         else{
             reverseStereo(wave, inputFiles[i]); //if wave is stereo
         }
         deallocWave(wave);
         free(wave);
     }
 }
References deallocWave(), wave::fmtChunk, initializeFromFile(), fmt_chunk::numChannels, reverseMono(), and reverseStereo().
Referenced by createReverseWave(), main(), reverseMono(), and reverseStereo().