AS4: speed.c File Reference
speed.c File Reference
implements speed.h
#include "wave.h"
Functions
void changeSpeed (char *fileName, float speedMult)
multiplies the speed of the wave file
Detailed Description
implements speed.h
Author
Nikolas Theodorou (ntheo.nosp@m.d10@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-11-29
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details in the COPYING file.
See license in COPYING file.
Copyright
Copyright (c) 2021
Function Documentation
changeSpeed()
void changeSpeed (char * fileName, float speedMult)
multiplies the speed of the wave file
Parameters
fileName
speedMult
{
     WAVE *wave = (WAVE*) malloc(sizeof(WAVE));
     initializeFromFile(wave,fileName);      //initialize wave file from file
     wave->fmtChunk->sampleRate *= speedMult;    //change sample Rate to fast forward or slow down
     exportWave(fileName,wave,"speed-"); //export file
     deallocWave(wave);      //free memory
     free(wave);
 }
References deallocWave(), exportWave(), wave::fmtChunk, initializeFromFile(), and fmt_chunk::sampleRate.
Referenced by main().