AS4: wave.h File Reference
wave.h File Reference
wave structure
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <ctype.h>
Data Structures
struct riff_chunk
struct fmt_chunk
struct data_chunk
struct wave
Typedefs
typedef unsigned char byte
typedef unsigned short int word
typedef unsigned int dword
typedef struct riff_chunk RIFF_CHUNK
typedef struct fmt_chunk FMT_CHUNK
typedef struct data_chunk DATA_CHUNK
typedef struct wave WAVE
Functions
void initialize (WAVE *wave)
initialize/allocate moemory for a wave
void initializeFromFile (WAVE *wave, char *fileName)
initializes a wave from a wavefile
void deallocWave (WAVE *wave)
deallocate memory of the wave
void exportWave (char *orgFileName, WAVE *wave, char *prefix)
export wave to a file
Detailed Description
wave structure
Author
Nikolas Theodorou (ntheo.nosp@m.d10@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-11-29
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details in the COPYING file.
See license in COPYING file.
Copyright
Copyright (c) 2021
Typedef Documentation
byte
typedef unsigned char byte
DATA_CHUNK
typedef struct data_chunk DATA_CHUNK
dword
typedef unsigned int dword
FMT_CHUNK
typedef struct fmt_chunk FMT_CHUNK
RIFF_CHUNK
typedef struct riff_chunk RIFF_CHUNK
WAVE
typedef struct wave WAVE
word
typedef unsigned short int word
Function Documentation
deallocWave()
void deallocWave (WAVE * wave)
deallocate memory of the wave
Parameters
wave
{
         free(wave->fmtChunk);
     free(wave->riffChunk);
     free(wave->dataChunk->data);
         free(wave->dataChunk);
 }
References data_chunk::data, wave::dataChunk, wave::fmtChunk, and wave::riffChunk.
Referenced by changeSpeed(), checkTimings(), chop(), cut(), decode(), encode(), isValidWaveFile(), list(), mixWaves(), reverseMono(), reverseStereo(), reverseWave(), stereoToMono(), and txtFitsWav().
exportWave()
void exportWave (char * orgFileName, WAVE * wave, char * prefix)
export wave to a file
Parameters
orgFileName original file name
wave wave to export
prefix prefix to the original file name
creates output file name
write wave file to file
{
     char *outputFile = NULL; //output file name
     outputFile = (char*)calloc(1,strlen(orgFileName)+strlen(prefix)+1);
     strcat(outputFile, prefix);
     strcat(outputFile, orgFileName);
     FILE *outfp = fopen(outputFile,"wb");
     fwrite(wave->riffChunk,sizeof(RIFF_CHUNK),1,outfp);
     fwrite(wave->fmtChunk,sizeof(FMT_CHUNK),1,outfp);
     fwrite(wave->dataChunk,sizeof(byte)*4+sizeof(dword),1,outfp);
     fwrite(wave->dataChunk->data ,wave->dataChunk->subchunk2Size,1,outfp);
     fclose(outfp);
     free(outputFile);
 }
References data_chunk::data, wave::dataChunk, wave::fmtChunk, wave::riffChunk, and data_chunk::subchunk2Size.
Referenced by changeSpeed(), chop(), cut(), encode(), mixWaves(), reverseMono(), reverseStereo(), and stereoToMono().
initialize()
void initialize (WAVE * wave)
initialize/allocate moemory for a wave
Parameters
wave
{
         wave->dataChunk = (DATA_CHUNK*)malloc(sizeof(DATA_CHUNK));
     wave->riffChunk = (RIFF_CHUNK*)malloc(sizeof(RIFF_CHUNK));
         wave->fmtChunk = (FMT_CHUNK*)malloc(sizeof(FMT_CHUNK));
 }
References wave::dataChunk, wave::fmtChunk, and wave::riffChunk.
initializeFromFile()
void initializeFromFile (WAVE * wave, char * fileName)
initializes a wave from a wavefile
Parameters
wave allocate memory for wave before using the method
fileName .wav file name
allocate memory for chunks
read from wave file
allocate memory and read the data
{
     FILE *fp = NULL;
     fp = fopen(fileName, "rb");
     if(fp==NULL){
         printf("file could not be opened or not found\n");
         exit(-1);
     }
         wave->dataChunk = (DATA_CHUNK*)malloc(sizeof(DATA_CHUNK));
     wave->riffChunk = (RIFF_CHUNK*)malloc(sizeof(RIFF_CHUNK));
         wave->fmtChunk = (FMT_CHUNK*)malloc(sizeof(FMT_CHUNK));
     fread(wave->riffChunk,sizeof(RIFF_CHUNK),1,fp);
         fread(wave->fmtChunk,sizeof(FMT_CHUNK),1,fp);
         fread(wave->dataChunk,4+sizeof(dword),1,fp);
     wave->dataChunk->data= (byte*) malloc(wave->dataChunk->subchunk2Size);
     fread(wave->dataChunk->data,wave->dataChunk->subchunk2Size,1,fp);
     fclose(fp);
 }
References data_chunk::data, wave::dataChunk, wave::fmtChunk, wave::riffChunk, and data_chunk::subchunk2Size.
Referenced by changeSpeed(), checkTimings(), chop(), createMixWave(), createReverseWave(), cut(), decode(), encode(), initializeToMono(), isValidWaveFile(), list(), mixWaves(), reverseWave(), stereoToMono(), and txtFitsWav().